apiVersion: v1
kind: Template
metadata:
  name: sources-availability
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: sources-availability
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: dummy
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true # port 8000 is default in ClowdEnvironment
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: SOURCES_SCHEME
          value: ${SOURCES_SCHEME}
        - name: SOURCES_HOST
          value: ${SOURCES_HOST}
        - name: SOURCES_PORT
          value: ${SOURCES_PORT}
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
    kafkaTopics:
    - topicName: platform.sources.event-stream
      partitions: 3
      replicas: 3
    - topicName: platform.sources.status
      partitions: 3
      replicas: 3
    inMemoryDb: false

parameters:
- description: Image
  name: IMAGE
  value: quay.io/jlindgren/availability-dummy
- description: Image tag
  name: IMAGE_TAG
  required: true
  value: latest
- name: CPU_LIMIT
  value: 500m
- name: CPU_REQUEST
  value: 100m
- name: MEMORY_LIMIT
  value: 1Gi
- name: MEMORY_REQUEST
  value: 500Mi
- description: The number of replicas to use for the prometheus deploy
  name: MIN_REPLICAS
  value: '1'
- description: Clowder ENV
  name: ENV_NAME
  required: true
- name: SOURCES_SCHEME
  displayName: Sources Service Scheme
  description: Scheme to use for the Sources service URL.
  value: http
- name: SOURCES_HOST
  displayName: Sources Service Host
  description: Host to use for the Sources service URL.
  value: sources-api-svc
- name: SOURCES_PORT
  displayName: Sources Service Port
  description: Port to use for the Sources service URL.
  value: "8000"
